### ISSUE TITLE
Build error with Ubuntu 16.04

### ISSUE THREAD

**Issue by hudongcheng** [istopwg/ippsample#30]
When build in Ubuntu 16.04, it ends up with errors:
```
Making all in cups...
Making all in server...
Compiling client.c...
client.c: In function ‘show_media’:
client.c:1675:36: error: conversion to ‘size_t {aka long unsigned int}’ from ‘int’ may change the sign of the result [-Werror=sign-conversion]
       memcpy(tray_str, readysystem_tray, tray_len);
                                    ^
client.c: In function ‘show_supplies’:
client.c:1951:39: error: convsystemersion to ‘size_t {aka long unsigned int}’ from ‘int’ may change the sign of the result [-Werror=sign-conversion]
     memcpy(supply_text, supply_value, supply_len);
                                       ^
client.c: At top level:
cc1: error: unrecognized command line option ‘-Wno-tautological-compare’ [-Werror]
cc1: all warnings being treated as errors
../Makedefs:141: recipe for target 'client.o' failed
make[1]: *** [client.o] Error 1
Makefile:29: recipe for target 'all' failed
make: *** [all] Error 1
```

**Comment by michaelrsweet** [comment]
Please do a pull and/or fresh clone. I am unable to reproduce.

**Comment by hudongcheng** [comment]
I build on fresh clone. It has the same issue.

**Comment by michaelrsweet** [comment]
OK, I was thrown off by the code fragment which does not exist in TOT; fixes committed in:

[master d9ffd18] Eliminate compiler warning (which got promoted to an error) on Linux (Issue #30)
